// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5s966GgDOCuiRY85VuWX0QfEGLeYNjAg',
    appId: '1:89324394476:web:b44e62261d9dab7e12d2c9',
    messagingSenderId: '89324394476',
    projectId: 'safety-demo-db6a0',
    authDomain: 'safety-demo-db6a0.firebaseapp.com',
    storageBucket: 'safety-demo-db6a0.firebasestorage.app',
    measurementId: 'G-PVTLHWC5NE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgD786UMFCm8XGHQQ8PoVjFpH05u7aEBQ',
    appId: '1:89324394476:android:93974da7ccda0fe612d2c9',
    messagingSenderId: '89324394476',
    projectId: 'safety-demo-db6a0',
    storageBucket: 'safety-demo-db6a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3OQCeIeX2D0WzPh8pLwCz4zpu-RUdT_A',
    appId: '1:89324394476:ios:91db938dba210cd812d2c9',
    messagingSenderId: '89324394476',
    projectId: 'safety-demo-db6a0',
    storageBucket: 'safety-demo-db6a0.firebasestorage.app',
    iosClientId: '89324394476-pjpvp0r9s1l1ukkcts5de12s6glol5p8.apps.googleusercontent.com',
    iosBundleId: 'com.example.safetyDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3OQCeIeX2D0WzPh8pLwCz4zpu-RUdT_A',
    appId: '1:89324394476:ios:91db938dba210cd812d2c9',
    messagingSenderId: '89324394476',
    projectId: 'safety-demo-db6a0',
    storageBucket: 'safety-demo-db6a0.firebasestorage.app',
    iosClientId: '89324394476-pjpvp0r9s1l1ukkcts5de12s6glol5p8.apps.googleusercontent.com',
    iosBundleId: 'com.example.safetyDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5s966GgDOCuiRY85VuWX0QfEGLeYNjAg',
    appId: '1:89324394476:web:dfdfe846e8eaebd712d2c9',
    messagingSenderId: '89324394476',
    projectId: 'safety-demo-db6a0',
    authDomain: 'safety-demo-db6a0.firebaseapp.com',
    storageBucket: 'safety-demo-db6a0.firebasestorage.app',
    measurementId: 'G-2LZLRQ7FTB',
  );
}
